name: benchmark

on:
  workflow_dispatch:

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15, windows-2025]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-pixi

      # Bazel's default output root on Windows is too deep for Windows paths.
      - name: Build scan_benchmark
        run: |
          if [ "$RUNNER_OS" = Windows ]; then
            echo "startup --output_user_root=C:/b" > user.bazelrc
          fi
          pixi run build RelWithDebInfo -- //:bin/scan_benchmark

      - name: Clone LLVM
        run: git clone --depth 1 https://github.com/llvm/llvm-project.git

      - name: Generate CDB
        run: |
          cmake -B llvm-build -G Ninja \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
            -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;lld;lldb;mlir;polly;flang;bolt" \
            -DLLVM_ENABLE_RUNTIMES="compiler-rt;libcxx;libcxxabi;libunwind" \
            llvm-project/llvm

      - name: Run benchmark
        run: ./build/RelWithDebInfo/bin/bin/scan_benchmark --runs 20 llvm-build/compile_commands.json
