name: cmake

on:
  workflow_call:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04, macos-15]
        build_type: [Debug, RelWithDebInfo]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-pixi

      - name: Build
        run: pixi run build ${{ matrix.build_type }} ON

      - name: Test
        run: pixi run unit-test ${{ matrix.build_type }}
